ANCESTRY_LIST = {
    "Anadi": "./pathfinder_bot/data/ancestries/anadi.json",
    "Android": "./pathfinder_bot/data/ancestries/android.json",
    "Athamaru": "./pathfinder_bot/data/ancestries/athamaru.json",
    "Automaton": "./pathfinder_bot/data/ancestries/automaton.json",
    "Awakened Animal": "./pathfinder_bot/data/ancestries/awakened-animal.json",
    "Azarketi": "./pathfinder_bot/data/ancestries/azarketi.json",
    "Catfolk": "./pathfinder_bot/data/ancestries/catfolk.json",
    "Centaur": "./pathfinder_bot/data/ancestries/centaur.json",
    "Conrasu": "./pathfinder_bot/data/ancestries/conrasu.json",
    "Dwarf": "./pathfinder_bot/data/ancestries/dwarf.json",
    "Elf": "./pathfinder_bot/data/ancestries/elf.json",
    "Fetchling": "./pathfinder_bot/data/ancestries/fetchling.json",
    "Fleshwarp": "./pathfinder_bot/data/ancestries/fleshwarp.json",
    "Ghoran": "./pathfinder_bot/data/ancestries/ghoran.json",
    "Gnome": "./pathfinder_bot/data/ancestries/gnome.json",
    "Goblin": "./pathfinder_bot/data/ancestries/goblin.json",
    "Goloma": "./pathfinder_bot/data/ancestries/goloma.json",
    "Halfling": "./pathfinder_bot/data/ancestries/halfling.json",
    "Hobgoblin": "./pathfinder_bot/data/ancestries/hobgoblin.json",
    "Human": "./pathfinder_bot/data/ancestries/human.json",
    "Kashrishi": "./pathfinder_bot/data/ancestries/kashrishi.json",
    "Kholo": "./pathfinder_bot/data/ancestries/kholo.json",
    "Kitsune": "./pathfinder_bot/data/ancestries/kitsune.json",
    "Kobold": "./pathfinder_bot/data/ancestries/kobold.json",
    "Leshy": "./pathfinder_bot/data/ancestries/leshy.json",
    "Lizardfolk": "./pathfinder_bot/data/ancestries/lizardfolk.json",
    "Merfolk": "./pathfinder_bot/data/ancestries/merfolk.json",
    "Minotaur": "./pathfinder_bot/data/ancestries/minotaur.json",
    "Nagaji": "./pathfinder_bot/data/ancestries/nagaji.json",
    "Orc": "./pathfinder_bot/data/ancestries/orc.json",
    "Poppet": "./pathfinder_bot/data/ancestries/poppet.json",
    "Ratfolk": "./pathfinder_bot/data/ancestries/ratfolk.json",
    "Samsaran": "./pathfinder_bot/data/ancestries/samsaran.json",
    "Sarangay": "./pathfinder_bot/data/ancestries/sarangay.json",
    "Shisk": "./pathfinder_bot/data/ancestries/shisk.json",
    "Shoony": "./pathfinder_bot/data/ancestries/shoony.json",
    "Skeleton": "./pathfinder_bot/data/ancestries/skeleton.json",
    "Sprite": "./pathfinder_bot/data/ancestries/sprite.json",
    "Strix": "./pathfinder_bot/data/ancestries/strix.json",
    "Surki": "./pathfinder_bot/data/ancestries/surki.json",
    "Tanuki": "./pathfinder_bot/data/ancestries/tanuki.json",
    "Tengu": "./pathfinder_bot/data/ancestries/tengu.json",
    "Tripkee": "./pathfinder_bot/data/ancestries/tripkee.json",
    "Vanara": "./pathfinder_bot/data/ancestries/vanara.json",
    "Vishkanya": "./pathfinder_bot/data/ancestries/vishkanya.json",
    "Wayang": "./pathfinder_bot/data/ancestries/wayang.json",
    "Yaksha": "./pathfinder_bot/data/ancestries/yaksha.json",
    "Yaoguai": "./pathfinder_bot/data/ancestries/yaoguai.json",
}

BACKGROUND_LIST = {
    "Abadar's Avenger": "./pathfinder_bot/data/backgrounds/abadars-avenger.json",
    "Able Carter": "./pathfinder_bot/data/backgrounds/able-carter.json",
    "Academy Dropout": "./pathfinder_bot/data/backgrounds/academy-dropout.json",
    "Acolyte": "./pathfinder_bot/data/backgrounds/acolyte.json",
    "Acrobat": "./pathfinder_bot/data/backgrounds/acrobat.json",
    "Acupuncturist": "./pathfinder_bot/data/backgrounds/acupuncturist.json",
    "Aerialist": "./pathfinder_bot/data/backgrounds/aerialist.json",
    "Aiudara Seeker": "./pathfinder_bot/data/backgrounds/aiudara-seeker.json",
    "Alkenstar Outlaw": "./pathfinder_bot/data/backgrounds/alkenstar-outlaw.json",
    "Alkenstar Sojourner": "./pathfinder_bot/data/backgrounds/alkenstar-sojourner.json",
    "Alkenstar Tinker": "./pathfinder_bot/data/backgrounds/alkenstar-tinker.json",
    "Alloysmith": "./pathfinder_bot/data/backgrounds/alloysmith.json",
    "Almas Clerk": "./pathfinder_bot/data/backgrounds/almas-clerk.json",
    "Always Chosen Last": "./pathfinder_bot/data/backgrounds/always-chosen-last.json",
    "Amateur Director": "./pathfinder_bot/data/backgrounds/amateur-director.json",
    "Amnesiac": "./pathfinder_bot/data/backgrounds/amnesiac.json",
    "Animal Whisperer": "./pathfinder_bot/data/backgrounds/animal-whisperer.json",
    "Animal Wrangler": "./pathfinder_bot/data/backgrounds/animal-wrangler.json",
    "Anti-Magical": "./pathfinder_bot/data/backgrounds/anti-magical.json",
    "Anti-Tech Activist": "./pathfinder_bot/data/backgrounds/anti-tech-activist.json",
    "Archaeologist": "./pathfinder_bot/data/backgrounds/archaeologist.json",
    "Art Tutor": "./pathfinder_bot/data/backgrounds/art-tutor.json",
    "Artisan": "./pathfinder_bot/data/backgrounds/artisan.json",
    "Artist": "./pathfinder_bot/data/backgrounds/artist.json",
    "Aspiring Free-Captain": "./pathfinder_bot/data/backgrounds/aspiring-free-captain.json",
    "Aspiring River Monarch": "./pathfinder_bot/data/backgrounds/aspiring-river-monarch.json",
    "Astrologer": "./pathfinder_bot/data/backgrounds/astrologer.json",
    "Astrological Augur": "./pathfinder_bot/data/backgrounds/astrological-augur.json",
    "Attention Addict": "./pathfinder_bot/data/backgrounds/attention-addict.json",
    "Atteran Rancher": "./pathfinder_bot/data/backgrounds/atteran-rancher.json",
    "Awful Scab": "./pathfinder_bot/data/backgrounds/awful-scab.json",
    "Bachuan Revolutionary": "./pathfinder_bot/data/backgrounds/bachuan-revolutionary.json",
    "Back-Alley Doctor": "./pathfinder_bot/data/backgrounds/back-alley-doctor.json",
    "Badlands Scout": "./pathfinder_bot/data/backgrounds/badlands-scout.json",
    "Bandit": "./pathfinder_bot/data/backgrounds/bandit.json",
    "Banished Brighite": "./pathfinder_bot/data/backgrounds/banished-brighite.json",
    "Banished Celestial": "./pathfinder_bot/data/backgrounds/banished-celestial.json",
    "Barber": "./pathfinder_bot/data/backgrounds/barber.json",
    "Barkeep": "./pathfinder_bot/data/backgrounds/barkeep.json",
    "Barker": "./pathfinder_bot/data/backgrounds/barker.json",
    "Barrister": "./pathfinder_bot/data/backgrounds/barrister.json",
    "Beast Blessed": "./pathfinder_bot/data/backgrounds/beast-blessed.json",
    "Bekyar Restorer": "./pathfinder_bot/data/backgrounds/bekyar-restorer.json",
    "Belkzen Anthropologist": "./pathfinder_bot/data/backgrounds/belkzen-anthropologist.json",
    "Belkzen Slayer": "./pathfinder_bot/data/backgrounds/belkzen-slayer.json",
    "Bellflower Agent": "./pathfinder_bot/data/backgrounds/bellflower-agent.json",
    "Bibliophile": "./pathfinder_bot/data/backgrounds/bibliophile.json",
    "Black Market Smuggler": "./pathfinder_bot/data/backgrounds/black-market-smuggler.json",
    "Blessed": "./pathfinder_bot/data/backgrounds/blessed.json",
    "Blow-In": "./pathfinder_bot/data/backgrounds/blow-in.json",
    "Bonuwat Wavetouched": "./pathfinder_bot/data/backgrounds/bonuwat-wavetouched.json",
    "Bookish Providence": "./pathfinder_bot/data/backgrounds/bookish-providence.json",
    "Bookkeeper": "./pathfinder_bot/data/backgrounds/bookkeeper.json",
    "Borderlands Pioneer": "./pathfinder_bot/data/backgrounds/borderlands-pioneer.json",
    "Bounty Hunter": "./pathfinder_bot/data/backgrounds/bounty-hunter.json",
    "Brevic Noble": "./pathfinder_bot/data/backgrounds/brevic-noble.json",
    "Brevic Outcast": "./pathfinder_bot/data/backgrounds/brevic-outcast.json",
    "Bright Lion": "./pathfinder_bot/data/backgrounds/bright-lion.json",
    "Broken Tusk Recruiter": "./pathfinder_bot/data/backgrounds/broken-tusk-recruiter.json",
    "Bully or Baiter?": "./pathfinder_bot/data/backgrounds/bully-or-baiter.json",
    "Butcher": "./pathfinder_bot/data/backgrounds/butcher.json",
    "Cannoneer": "./pathfinder_bot/data/backgrounds/cannoneer.json",
    "Cathedral Child": "./pathfinder_bot/data/backgrounds/cathedral-child.json",
    "Charlatan": "./pathfinder_bot/data/backgrounds/charlatan.json",
    "Chelish Rebel": "./pathfinder_bot/data/backgrounds/chelish-rebel.json",
    "Child Of Notoriety": "./pathfinder_bot/data/backgrounds/child-of-notoriety.json",
    "Child of Westcrown": "./pathfinder_bot/data/backgrounds/child-of-westcrown.json",
    "Child of the Puddles": "./pathfinder_bot/data/backgrounds/child-of-the-puddles.json",
    "Child of the Twin Village": "./pathfinder_bot/data/backgrounds/child-of-the-twin-village.json",
    "Chosen One": "./pathfinder_bot/data/backgrounds/chosen-one.json",
    "Circuit Judge": "./pathfinder_bot/data/backgrounds/circuit-judge.json",
    "Circus Born": "./pathfinder_bot/data/backgrounds/circus-born.json",
    "Clan Associate": "./pathfinder_bot/data/backgrounds/clan-associate.json",
    "Clockfighter": "./pathfinder_bot/data/backgrounds/clockfighter.json",
    "Clockwork Researcher": "./pathfinder_bot/data/backgrounds/clockwork-researcher.json",
    "Close Ties": "./pathfinder_bot/data/backgrounds/close-ties.json",
    "Clown": "./pathfinder_bot/data/backgrounds/clown.json",
    "Codebreaker": "./pathfinder_bot/data/backgrounds/codebreaker.json",
    "Concordance Researcher": "./pathfinder_bot/data/backgrounds/concordance-researcher.json",
    "Concordance Scout": "./pathfinder_bot/data/backgrounds/concordance-scout.json",
    "Conservator": "./pathfinder_bot/data/backgrounds/conservator.json",
    "Construction Occultist": "./pathfinder_bot/data/backgrounds/construction-occultist.json",
    "Cook": "./pathfinder_bot/data/backgrounds/cook.json",
    "Corpse Stitcher": "./pathfinder_bot/data/backgrounds/corpse-stitcher.json",
    "Courier": "./pathfinder_bot/data/backgrounds/courier.json",
    "Criminal": "./pathfinder_bot/data/backgrounds/criminal.json",
    "Crown of Chaos": "./pathfinder_bot/data/backgrounds/crown-of-chaos.json",
    "Crystal Healer": "./pathfinder_bot/data/backgrounds/crystal-healer.json",
    "Cultist": "./pathfinder_bot/data/backgrounds/cultist.json",
    "Curandero": "./pathfinder_bot/data/backgrounds/curandero.json",
    "Curious Apprentice": "./pathfinder_bot/data/backgrounds/curious-apprentice.json",
    "Cursed": "./pathfinder_bot/data/backgrounds/cursed.json",
    "Cursed Family": "./pathfinder_bot/data/backgrounds/cursed-family.json",
    "Dauntless": "./pathfinder_bot/data/backgrounds/dauntless.json",
    "Deckhand": "./pathfinder_bot/data/backgrounds/deckhand.json",
    "Dedicated Delver": "./pathfinder_bot/data/backgrounds/dedicated-delver.json",
    "Deep-Sea Diver": "./pathfinder_bot/data/backgrounds/deep-sea-diver.json",
    "Demon Slayer": "./pathfinder_bot/data/backgrounds/demon-slayer.json",
    "Dendrologist": "./pathfinder_bot/data/backgrounds/dendrologist.json",
    "Deputy": "./pathfinder_bot/data/backgrounds/deputy.json",
    "Desert Tracker": "./pathfinder_bot/data/backgrounds/desert-tracker.json",
    "Detective": "./pathfinder_bot/data/backgrounds/detective.json",
    "Diobel Pearl Diver": "./pathfinder_bot/data/backgrounds/diobel-pearl-diver.json",
    "Discarded Duplicate": "./pathfinder_bot/data/backgrounds/discarded-duplicate.json",
    "Disciple of the Gear": "./pathfinder_bot/data/backgrounds/disciple-of-the-gear.json",
    "Doomcaller": "./pathfinder_bot/data/backgrounds/doomcaller.json",
    "Dragon Scholar": "./pathfinder_bot/data/backgrounds/dragon-scholar.json",
    "Dreamer of the Verdant Moon": "./pathfinder_bot/data/backgrounds/dreamer-of-the-verdant-moon.json",
    "Dreams of Vengeance": "./pathfinder_bot/data/backgrounds/dreams-of-vengeance.json",
    "Driver": "./pathfinder_bot/data/backgrounds/driver.json",
    "Droskari Disciple": "./pathfinder_bot/data/backgrounds/droskari-disciple.json",
    "Eager Scofflaw": "./pathfinder_bot/data/backgrounds/eager-scofflaw.json",
    "Eagle Hunter": "./pathfinder_bot/data/backgrounds/eagle-hunter.json",
    "Early Explorer": "./pathfinder_bot/data/backgrounds/early-explorer.json",
    "Eclectic Scholar": "./pathfinder_bot/data/backgrounds/eclectic-scholar.json",
    "Eclipseborn": "./pathfinder_bot/data/backgrounds/eclipseborn.json",
    "Eidolon Contact": "./pathfinder_bot/data/backgrounds/eidolon-contact.json",
    "Eldritch Anatomist": "./pathfinder_bot/data/backgrounds/eldritch-anatomist.json",
    "Elementally Infused": "./pathfinder_bot/data/backgrounds/elementally-infused.json",
    "Emancipated": "./pathfinder_bot/data/backgrounds/emancipated.json",
    "Emissary": "./pathfinder_bot/data/backgrounds/emissary.json",
    "Empty Hand Loyalist": "./pathfinder_bot/data/backgrounds/empty-hand-loyalist.json",
    "Empty Whispers": "./pathfinder_bot/data/backgrounds/empty-whispers.json",
    "Energy Scarred": "./pathfinder_bot/data/backgrounds/energy-scarred.json",
    "Entertainer": "./pathfinder_bot/data/backgrounds/entertainer.json",
    "Ex-Con Token Guard": "./pathfinder_bot/data/backgrounds/ex-con-token-guard.json",
    "Ex-Mendevian Crusader": "./pathfinder_bot/data/backgrounds/ex-mendevian-crusader.json",
    "Faction Opportunist": "./pathfinder_bot/data/backgrounds/faction-opportunist.json",
    "False Medium": "./pathfinder_bot/data/backgrounds/false-medium.json",
    "Farmhand": "./pathfinder_bot/data/backgrounds/farmhand.json",
    "Farmsteader": "./pathfinder_bot/data/backgrounds/farmsteader.json",
    "Fated Rival": "./pathfinder_bot/data/backgrounds/fated-rival.json",
    "Favored": "./pathfinder_bot/data/backgrounds/favored.json",
    "Feral Child": "./pathfinder_bot/data/backgrounds/feral-child.json",
    "Fey Friend": "./pathfinder_bot/data/backgrounds/fey-friend.json",
    "Feybound": "./pathfinder_bot/data/backgrounds/feybound.json",
    "Field Medic": "./pathfinder_bot/data/backgrounds/field-medic.json",
    "Fightbreaker": "./pathfinder_bot/data/backgrounds/fightbreaker.json",
    "Finadar Leshy": "./pathfinder_bot/data/backgrounds/finadar-leshy.json",
    "Final Blade Survivor": "./pathfinder_bot/data/backgrounds/final-blade-survivor.json",
    "Fire Warden": "./pathfinder_bot/data/backgrounds/fire-warden.json",
    "Firebrand Follower": "./pathfinder_bot/data/backgrounds/firebrand-follower.json",
    "Fireworks Performer": "./pathfinder_bot/data/backgrounds/fireworks-performer.json",
    "Fogfen Tale-Teller": "./pathfinder_bot/data/backgrounds/fogfen-tale-teller.json",
    "Folklore Enthusiast": "./pathfinder_bot/data/backgrounds/folklore-enthusiast.json",
    "Food Trader": "./pathfinder_bot/data/backgrounds/food-trader.json",
    "Foreign Diplomat": "./pathfinder_bot/data/backgrounds/foreign-diplomat.json",
    "Former Aspis Agent": "./pathfinder_bot/data/backgrounds/former-aspis-agent.json",
    "Fortune Teller": "./pathfinder_bot/data/backgrounds/fortune-teller.json",
    "Framed in Ferrous Quarter": "./pathfinder_bot/data/backgrounds/framed-in-ferrous-quarter.json",
    "Free Spirit": "./pathfinder_bot/data/backgrounds/free-spirit.json",
    "Freed Slave of Absalom": "./pathfinder_bot/data/backgrounds/freed-slave-of-absalom.json",
    "Friend of Greensteeples": "./pathfinder_bot/data/backgrounds/friend-of-greensteeples.json",
    "Friendly Darkmoon Kobold": "./pathfinder_bot/data/backgrounds/friendly-darkmoon-kobold.json",
    "Gambler": "./pathfinder_bot/data/backgrounds/gambler.json",
    "Geb Crusader": "./pathfinder_bot/data/backgrounds/geb-crusader.json",
    "Genie-Blessed": "./pathfinder_bot/data/backgrounds/genie-blessed.json",
    "Gladiator": "./pathfinder_bot/data/backgrounds/gladiator.json",
    "Gloriana's Fixer": "./pathfinder_bot/data/backgrounds/glorianas-fixer.json",
    "Goblinblood Orphan": "./pathfinder_bot/data/backgrounds/goblinblood-orphan.json",
    "Godless Graycloak": "./pathfinder_bot/data/backgrounds/godless-graycloak.json",
    "Gold Falls Regular": "./pathfinder_bot/data/backgrounds/gold-falls-regular.json",
    "Goldhand Arms Dealer": "./pathfinder_bot/data/backgrounds/goldhand-arms-dealer.json",
    "Gossip": "./pathfinder_bot/data/backgrounds/gossip.json",
    "Grand Council Bureaucrat": "./pathfinder_bot/data/backgrounds/grand-council-bureaucrat.json",
    "Grave Robber": "./pathfinder_bot/data/backgrounds/grave-robber.json",
    "Green Faith Pilgrim": "./pathfinder_bot/data/backgrounds/green-faith-pilgrim.json",
    "Grizzled Muckrucker": "./pathfinder_bot/data/backgrounds/grizzled-muckrucker.json",
    "Guard": "./pathfinder_bot/data/backgrounds/guard.json",
    "Guest of Sedeq Lodge": "./pathfinder_bot/data/backgrounds/guest-of-sedeq-lodge.json",
    "Gunsmith": "./pathfinder_bot/data/backgrounds/gunsmith.json",
    "Hammered by Fate": "./pathfinder_bot/data/backgrounds/hammered-by-fate.json",
    "Harbor Guard Moonlighter": "./pathfinder_bot/data/backgrounds/harbor-guard-moonlighter.json",
    "Harrow-Chosen": "./pathfinder_bot/data/backgrounds/harrow-chosen.json",
    "Harrow-Led": "./pathfinder_bot/data/backgrounds/harrow-led.json",
    "Haunted": "./pathfinder_bot/data/backgrounds/haunted.json",
    "Haunted Citizen": "./pathfinder_bot/data/backgrounds/haunted-citizen.json",
    "Haunting Vision": "./pathfinder_bot/data/backgrounds/haunting-vision.json",
    "Hellknight Historian": "./pathfinder_bot/data/backgrounds/hellknight-historian.json",
    "Herbalist": "./pathfinder_bot/data/backgrounds/herbalist.json",
    "Hermean Expatriate": "./pathfinder_bot/data/backgrounds/hermean-expatriate.json",
    "Hermean Heritor": "./pathfinder_bot/data/backgrounds/hermean-heritor.json",
    "Hermit": "./pathfinder_bot/data/backgrounds/hermit.json",
    "Highborn Snoop": "./pathfinder_bot/data/backgrounds/highborn-snoop.json",
    "Hired Killer": "./pathfinder_bot/data/backgrounds/hired-killer.json",
    "Historical Reenactor": "./pathfinder_bot/data/backgrounds/historical-reenactor.json",
    "Hookclaw Digger": "./pathfinder_bot/data/backgrounds/hookclaw-digger.json",
    "Hounded Thief": "./pathfinder_bot/data/backgrounds/hounded-thief.json",
    "Hunter": "./pathfinder_bot/data/backgrounds/hunter.json",
    "Inexplicably Expelled": "./pathfinder_bot/data/backgrounds/inexplicably-expelled.json",
    "Inlander": "./pathfinder_bot/data/backgrounds/inlander.json",
    "Insurgent": "./pathfinder_bot/data/backgrounds/insurgent.json",
    "Iolite Trainee Hobgoblin": "./pathfinder_bot/data/backgrounds/iolite-trainee-hobgoblin.json",
    "Issian Partisan": "./pathfinder_bot/data/backgrounds/issian-partisan.json",
    "Issian Patriot": "./pathfinder_bot/data/backgrounds/issian-patriot.json",
    "Jeweler": "./pathfinder_bot/data/backgrounds/jeweler.json",
    "Junk Collector": "./pathfinder_bot/data/backgrounds/junk-collector.json",
    "Junker": "./pathfinder_bot/data/backgrounds/junker.json",
    "Kaiju Stalker": "./pathfinder_bot/data/backgrounds/kaiju-stalker.json",
    "Kalistrade Follower": "./pathfinder_bot/data/backgrounds/kalistrade-follower.json",
    "Keys to Destiny": "./pathfinder_bot/data/backgrounds/keys-to-destiny.json",
    "Kyonin Emissary": "./pathfinder_bot/data/backgrounds/kyonin-emissary.json",
    "Laborer": "./pathfinder_bot/data/backgrounds/laborer.json",
    "Lastwall Survivor": "./pathfinder_bot/data/backgrounds/lastwall-survivor.json",
    "Learned Guard Prodigy": "./pathfinder_bot/data/backgrounds/learned-guard-prodigy.json",
    "Legacy of the Hammer": "./pathfinder_bot/data/backgrounds/legacy-of-the-hammer.json",
    "Legendary Parents": "./pathfinder_bot/data/backgrounds/legendary-parents.json",
    "Lesser Scion": "./pathfinder_bot/data/backgrounds/lesser-scion.json",
    "Local Brigand": "./pathfinder_bot/data/backgrounds/local-brigand.json",
    "Local Scion": "./pathfinder_bot/data/backgrounds/local-scion.json",
    "Lost Coast Local": "./pathfinder_bot/data/backgrounds/lost-coast-local.json",
    "Lost Loved One": "./pathfinder_bot/data/backgrounds/lost-loved-one.json",
    "Lost and Alone": "./pathfinder_bot/data/backgrounds/lost-and-alone.json",
    "Lumber Consortium Laborer": "./pathfinder_bot/data/backgrounds/lumber-consortium-laborer.json",
    "Magaambya Academic": "./pathfinder_bot/data/backgrounds/magaambya-academic.json",
    "Magical Experiment": "./pathfinder_bot/data/backgrounds/magical-experiment.json",
    "Magical Merchant": "./pathfinder_bot/data/backgrounds/magical-merchant.json",
    "Magical Misfit": "./pathfinder_bot/data/backgrounds/magical-misfit.json",
    "Mammoth Herder": "./pathfinder_bot/data/backgrounds/mammoth-herder.json",
    "Mammoth Speaker": "./pathfinder_bot/data/backgrounds/mammoth-speaker.json",
    "Mana Wastes Refugee": "./pathfinder_bot/data/backgrounds/mana-wastes-refugee.json",
    "Mantis Scion": "./pathfinder_bot/data/backgrounds/mantis-scion.json",
    "Market Runner": "./pathfinder_bot/data/backgrounds/market-runner.json",
    "Martial Disciple": "./pathfinder_bot/data/backgrounds/martial-disciple.json",
    "Mechanic": "./pathfinder_bot/data/backgrounds/mechanic.json",
    "Mechanical Symbiosis": "./pathfinder_bot/data/backgrounds/mechanical-symbiosis.json",
    "Medicinal Clocksmith": "./pathfinder_bot/data/backgrounds/medicinal-clocksmith.json",
    "Megafauna Hunter": "./pathfinder_bot/data/backgrounds/megafauna-hunter.json",
    "Menagerie Dung Sweeper": "./pathfinder_bot/data/backgrounds/menagerie-dung-sweeper.json",
    "Merabite Prodigy": "./pathfinder_bot/data/backgrounds/merabite-prodigy.json",
    "Merchant": "./pathfinder_bot/data/backgrounds/merchant.json",
    "Militia Member": "./pathfinder_bot/data/backgrounds/militia-member.json",
    "Miner": "./pathfinder_bot/data/backgrounds/miner.json",
    "Missionary": "./pathfinder_bot/data/backgrounds/missionary.json",
    "Molthuni Mercenary": "./pathfinder_bot/data/backgrounds/molthuni-mercenary.json",
    "Money Counter": "./pathfinder_bot/data/backgrounds/money-counter.json",
    "Moot Guard": "./pathfinder_bot/data/backgrounds/moot-guard.json",
    "Mortuarium Survivor": "./pathfinder_bot/data/backgrounds/mortuarium-survivor.json",
    "Musical Prodigy": "./pathfinder_bot/data/backgrounds/musical-prodigy.json",
    "Mystic Seer": "./pathfinder_bot/data/backgrounds/mystic-seer.json",
    "Mystic Tutor": "./pathfinder_bot/data/backgrounds/mystic-tutor.json",
    "Necromancer's Apprentice": "./pathfinder_bot/data/backgrounds/necromancers-apprentice.json",
    "Newcomer": "./pathfinder_bot/data/backgrounds/newcomer.json",
    "Newcomer In Need": "./pathfinder_bot/data/backgrounds/newcomer-in-need.json",
    "Nexian Mystic": "./pathfinder_bot/data/backgrounds/nexian-mystic.json",
    "Night Watch": "./pathfinder_bot/data/backgrounds/night-watch.json",
    "Nirmathi Guerrilla": "./pathfinder_bot/data/backgrounds/nirmathi-guerrilla.json",
    "Noble": "./pathfinder_bot/data/backgrounds/noble.json",
    "Nocturnal Navigator": "./pathfinder_bot/data/backgrounds/nocturnal-navigator.json",
    "Nomad": "./pathfinder_bot/data/backgrounds/nomad.json",
    "Northland Forager": "./pathfinder_bot/data/backgrounds/northland-forager.json",
    "Northridge Scholar": "./pathfinder_bot/data/backgrounds/northridge-scholar.json",
    "Occult Librarian": "./pathfinder_bot/data/backgrounds/occult-librarian.json",
    "Ocean Diver": "./pathfinder_bot/data/backgrounds/ocean-diver.json",
    "Oenopion-Ooze Tender": "./pathfinder_bot/data/backgrounds/oenopion-ooze-tender.json",
    "Once Bitten": "./pathfinder_bot/data/backgrounds/once-bitten.json",
    "Onyx Trader": "./pathfinder_bot/data/backgrounds/onyx-trader.json",
    "Osirionologist": "./pathfinder_bot/data/backgrounds/osirionologist.json",
    "Osprey Barnraiser": "./pathfinder_bot/data/backgrounds/osprey-barnraiser.json",
    "Osprey Fisher": "./pathfinder_bot/data/backgrounds/osprey-fisher.json",
    "Osprey Scion": "./pathfinder_bot/data/backgrounds/osprey-scion.json",
    "Osprey Scout": "./pathfinder_bot/data/backgrounds/osprey-scout.json",
    "Osprey Scribe": "./pathfinder_bot/data/backgrounds/osprey-scribe.json",
    "Osprey Spellcaster": "./pathfinder_bot/data/backgrounds/osprey-spellcaster.json",
    "Osprey Warrior": "./pathfinder_bot/data/backgrounds/osprey-warrior.json",
    "Otherworldly Mission": "./pathfinder_bot/data/backgrounds/otherworldly-mission.json",
    "Out-Of-Towner": "./pathfinder_bot/data/backgrounds/out-of-towner.json",
    "Outrider": "./pathfinder_bot/data/backgrounds/outrider.json",
    "Outskirt Dweller": "./pathfinder_bot/data/backgrounds/outskirt-dweller.json",
    "Ozem Experience": "./pathfinder_bot/data/backgrounds/ozem-experience.json",
    "Pathfinder Hopeful": "./pathfinder_bot/data/backgrounds/pathfinder-hopeful.json",
    "Pathfinder Recruiter": "./pathfinder_bot/data/backgrounds/pathfinder-recruiter.json",
    "Perfection Seeker": "./pathfinder_bot/data/backgrounds/perfection-seeker.json",
    "Pilgrim": "./pathfinder_bot/data/backgrounds/pilgrim.json",
    "Pillar": "./pathfinder_bot/data/backgrounds/pillar.json",
    "Planar Migrant": "./pathfinder_bot/data/backgrounds/planar-migrant.json",
    "Plant Whisperer": "./pathfinder_bot/data/backgrounds/plant-whisperer.json",
    "Political Scion": "./pathfinder_bot/data/backgrounds/political-scion.json",
    "Post Guard of All Trades": "./pathfinder_bot/data/backgrounds/post-guard-of-all-trades.json",
    "Press-Ganged (G&G)": "./pathfinder_bot/data/backgrounds/press-ganged-g-g.json",
    "Press-Ganged (LOWG)": "./pathfinder_bot/data/backgrounds/press-ganged-lowg.json",
    "Printer": "./pathfinder_bot/data/backgrounds/printer.json",
    "Prisoner": "./pathfinder_bot/data/backgrounds/prisoner.json",
    "Professional Letter Writer": "./pathfinder_bot/data/backgrounds/professional-letter-writer.json",
    "Propaganda Promoter": "./pathfinder_bot/data/backgrounds/propaganda-promoter.json",
    "Purveyor of the Bizarre": "./pathfinder_bot/data/backgrounds/purveyor-of-the-bizarre.json",
    "Pyre Tender": "./pathfinder_bot/data/backgrounds/pyre-tender.json",
    "Quick": "./pathfinder_bot/data/backgrounds/quick.json",
    "Quick Refugee": "./pathfinder_bot/data/backgrounds/quick-refugee.json",
    "Raised by Belief": "./pathfinder_bot/data/backgrounds/raised-by-belief.json",
    "Ratted-Out Gun Runner": "./pathfinder_bot/data/backgrounds/ratted-out-gun-runner.json",
    "Razmiran Faithful": "./pathfinder_bot/data/backgrounds/razmiran-faithful.json",
    "Reborn Soul": "./pathfinder_bot/data/backgrounds/reborn-soul.json",
    "Reclaimed": "./pathfinder_bot/data/backgrounds/reclaimed.json",
    "Reclaimer Investigator": "./pathfinder_bot/data/backgrounds/reclaimer-investigator.json",
    "Refugee (Fall of Plaguestone)": "./pathfinder_bot/data/backgrounds/refugee-fall-of-plaguestone.json",
    "Refugee (PC2)": "./pathfinder_bot/data/backgrounds/refugee-pc2.json",
    "Relentless Dedication": "./pathfinder_bot/data/backgrounds/relentless-dedication.json",
    "Remittance Agent": "./pathfinder_bot/data/backgrounds/remittance-agent.json",
    "Reputation Seeker": "./pathfinder_bot/data/backgrounds/reputation-seeker.json",
    "Returned": "./pathfinder_bot/data/backgrounds/returned.json",
    "Returning Descendant": "./pathfinder_bot/data/backgrounds/returning-descendant.json",
    "Revenant": "./pathfinder_bot/data/backgrounds/revenant.json",
    "Rigger": "./pathfinder_bot/data/backgrounds/rigger.json",
    "Rivethun Adherent": "./pathfinder_bot/data/backgrounds/rivethun-adherent.json",
    "Root Worker": "./pathfinder_bot/data/backgrounds/root-worker.json",
    "Rostland Partisan": "./pathfinder_bot/data/backgrounds/rostland-partisan.json",
    "Rostlander": "./pathfinder_bot/data/backgrounds/rostlander.json",
    "Royalty": "./pathfinder_bot/data/backgrounds/royalty.json",
    "Ruby Phoenix Enthusiast": "./pathfinder_bot/data/backgrounds/ruby-phoenix-enthusiast.json",
    "Ruby Phoenix Fanatic": "./pathfinder_bot/data/backgrounds/ruby-phoenix-fanatic.json",
    "Ruin Delver": "./pathfinder_bot/data/backgrounds/ruin-delver.json",
    "Runaway Noble": "./pathfinder_bot/data/backgrounds/runaway-noble.json",
    "Runelord Scholar": "./pathfinder_bot/data/backgrounds/runelord-scholar.json",
    "Runner": "./pathfinder_bot/data/backgrounds/runner.json",
    "Saboteur": "./pathfinder_bot/data/backgrounds/saboteur.json",
    "Sailor": "./pathfinder_bot/data/backgrounds/sailor.json",
    "Sally Guard Neophyte": "./pathfinder_bot/data/backgrounds/sally-guard-neophyte.json",
    "Saloon Entertainer": "./pathfinder_bot/data/backgrounds/saloon-entertainer.json",
    "Sandswept Survivor": "./pathfinder_bot/data/backgrounds/sandswept-survivor.json",
    "Sarkorian Reclaimer": "./pathfinder_bot/data/backgrounds/sarkorian-reclaimer.json",
    "Sarkorian Survivor": "./pathfinder_bot/data/backgrounds/sarkorian-survivor.json",
    "Saved by Clockwork": "./pathfinder_bot/data/backgrounds/saved-by-clockwork.json",
    "Savior of Air": "./pathfinder_bot/data/backgrounds/savior-of-air.json",
    "Scarnetti-Connected": "./pathfinder_bot/data/backgrounds/scarnetti-connected.json",
    "Scavenger": "./pathfinder_bot/data/backgrounds/scavenger.json",
    "Scholar": "./pathfinder_bot/data/backgrounds/scholar.json",
    "Scholar of the Ancients": "./pathfinder_bot/data/backgrounds/scholar-of-the-ancients.json",
    "Scholar of the Sky Key": "./pathfinder_bot/data/backgrounds/scholar-of-the-sky-key.json",
    "Scion of Slayers": "./pathfinder_bot/data/backgrounds/scion-of-slayers.json",
    "Scout": "./pathfinder_bot/data/backgrounds/scout.json",
    "Second Chance Champion": "./pathfinder_bot/data/backgrounds/second-chance-champion.json",
    "Secular Medic": "./pathfinder_bot/data/backgrounds/secular-medic.json",
    "Seer of the Dead": "./pathfinder_bot/data/backgrounds/seer-of-the-dead.json",
    "Self-Made": "./pathfinder_bot/data/backgrounds/self-made.json",
    "Senghor Sailor": "./pathfinder_bot/data/backgrounds/senghor-sailor.json",
    "Sense of Belonging": "./pathfinder_bot/data/backgrounds/sense-of-belonging.json",
    "Sentinel Reflectance": "./pathfinder_bot/data/backgrounds/sentinel-reflectance.json",
    "Servant": "./pathfinder_bot/data/backgrounds/servant.json",
    "Sewer Dragon": "./pathfinder_bot/data/backgrounds/sewer-dragon.json",
    "Shadow Haunted": "./pathfinder_bot/data/backgrounds/shadow-haunted.json",
    "Shadow Lodge Defector": "./pathfinder_bot/data/backgrounds/shadow-lodge-defector.json",
    "Shadow War Survivor": "./pathfinder_bot/data/backgrounds/shadow-war-survivor.json",
    "Sheriff": "./pathfinder_bot/data/backgrounds/sheriff.json",
    "Shielded Fortune": "./pathfinder_bot/data/backgrounds/shielded-fortune.json",
    "Shoanti Name-Bearer": "./pathfinder_bot/data/backgrounds/shoanti-name-bearer.json",
    "Shory Seeker": "./pathfinder_bot/data/backgrounds/shory-seeker.json",
    "Sideshow Scion": "./pathfinder_bot/data/backgrounds/sideshow-scion.json",
    "Sign Bound": "./pathfinder_bot/data/backgrounds/sign-bound.json",
    "Silk Farmer": "./pathfinder_bot/data/backgrounds/silk-farmer.json",
    "Sky Rider": "./pathfinder_bot/data/backgrounds/sky-rider.json",
    "Sleepless Suns Star": "./pathfinder_bot/data/backgrounds/sleepless-suns-star.json",
    "Snubbed Out Stoolie": "./pathfinder_bot/data/backgrounds/snubbed-out-stoolie.json",
    "Sodden Scavenger": "./pathfinder_bot/data/backgrounds/sodden-scavenger.json",
    "Song of the Deep": "./pathfinder_bot/data/backgrounds/song-of-the-deep.json",
    "Songsinger in Training": "./pathfinder_bot/data/backgrounds/songsinger-in-training.json",
    "Southbank Traditionalist": "./pathfinder_bot/data/backgrounds/southbank-traditionalist.json",
    "Spell Seeker": "./pathfinder_bot/data/backgrounds/spell-seeker.json",
    "Sponsored by Family": "./pathfinder_bot/data/backgrounds/sponsored-by-family.json",
    "Sponsored by Teacher Ot": "./pathfinder_bot/data/backgrounds/sponsored-by-teacher-ot.json",
    "Sponsored by a Stranger": "./pathfinder_bot/data/backgrounds/sponsored-by-a-stranger.json",
    "Sponsored by a Village": "./pathfinder_bot/data/backgrounds/sponsored-by-a-village.json",
    "Spotter": "./pathfinder_bot/data/backgrounds/spotter.json",
    "Squire": "./pathfinder_bot/data/backgrounds/squire.json",
    "Starless One": "./pathfinder_bot/data/backgrounds/starless-one.json",
    "Starwatcher": "./pathfinder_bot/data/backgrounds/starwatcher.json",
    "Storm Survivor": "./pathfinder_bot/data/backgrounds/storm-survivor.json",
    "Street Preacher": "./pathfinder_bot/data/backgrounds/street-preacher.json",
    "Street Urchin": "./pathfinder_bot/data/backgrounds/street-urchin.json",
    "Streetfood Vendor": "./pathfinder_bot/data/backgrounds/streetfood-vendor.json",
    "Student of Magic": "./pathfinder_bot/data/backgrounds/student-of-magic.json",
    "Sun Dancer": "./pathfinder_bot/data/backgrounds/sun-dancer.json",
    "Supportive Sponsor": "./pathfinder_bot/data/backgrounds/supportive-sponsor.json",
    "Surge Investigator": "./pathfinder_bot/data/backgrounds/surge-investigator.json",
    "Sword Scion": "./pathfinder_bot/data/backgrounds/sword-scion.json",
    "Taldan Schemer": "./pathfinder_bot/data/backgrounds/taldan-schemer.json",
    "Tall Tale": "./pathfinder_bot/data/backgrounds/tall-tale.json",
    "Tapestry Refugee": "./pathfinder_bot/data/backgrounds/tapestry-refugee.json",
    "Tax Collector": "./pathfinder_bot/data/backgrounds/tax-collector.json",
    "Teacher": "./pathfinder_bot/data/backgrounds/teacher.json",
    "Teamster": "./pathfinder_bot/data/backgrounds/teamster.json",
    "Tech Reliant": "./pathfinder_bot/data/backgrounds/tech-reliant.json",
    "Thassilonian Delver": "./pathfinder_bot/data/backgrounds/thassilonian-delver.json",
    "Thassilonian Traveler": "./pathfinder_bot/data/backgrounds/thassilonian-traveler.json",
    "Thrill-Seeker": "./pathfinder_bot/data/backgrounds/thrill-seeker.json",
    "Thrune Loyalist": "./pathfinder_bot/data/backgrounds/thrune-loyalist.json",
    "Thuvian Unifier": "./pathfinder_bot/data/backgrounds/thuvian-unifier.json",
    "Tide Watcher": "./pathfinder_bot/data/backgrounds/tide-watcher.json",
    "Tiffin Box Deliverer": "./pathfinder_bot/data/backgrounds/tiffin-box-deliverer.json",
    "Time Traveler": "./pathfinder_bot/data/backgrounds/time-traveler.json",
    "Tinker": "./pathfinder_bot/data/backgrounds/tinker.json",
    "Tomb Born": "./pathfinder_bot/data/backgrounds/tomb-born.json",
    "Total Power": "./pathfinder_bot/data/backgrounds/total-power.json",
    "Touched by Dahak": "./pathfinder_bot/data/backgrounds/touched-by-dahak.json",
    "Town Troublemaker": "./pathfinder_bot/data/backgrounds/town-troublemaker.json",
    "Toymaker": "./pathfinder_bot/data/backgrounds/toymaker.json",
    "Trade Consortium Underling": "./pathfinder_bot/data/backgrounds/trade-consortium-underling.json",
    "Trade Representative": "./pathfinder_bot/data/backgrounds/trade-representative.json",
    "Trailblazer": "./pathfinder_bot/data/backgrounds/trailblazer.json",
    "Translator": "./pathfinder_bot/data/backgrounds/translator.json",
    "Traveling Gourmand": "./pathfinder_bot/data/backgrounds/traveling-gourmand.json",
    "Tree Friend": "./pathfinder_bot/data/backgrounds/tree-friend.json",
    "Truth Seeker": "./pathfinder_bot/data/backgrounds/truth-seeker.json",
    "Tyrant Witness": "./pathfinder_bot/data/backgrounds/tyrant-witness.json",
    "Ulfen Raider": "./pathfinder_bot/data/backgrounds/ulfen-raider.json",
    "Undercover Contender": "./pathfinder_bot/data/backgrounds/undercover-contender.json",
    "Undercover Lotus Guard": "./pathfinder_bot/data/backgrounds/undercover-lotus-guard.json",
    "Undersea Enthusiast": "./pathfinder_bot/data/backgrounds/undersea-enthusiast.json",
    "Undertaker": "./pathfinder_bot/data/backgrounds/undertaker.json",
    "Union Representative": "./pathfinder_bot/data/backgrounds/union-representative.json",
    "Unremarkable": "./pathfinder_bot/data/backgrounds/unremarkable.json",
    "Unsponsored": "./pathfinder_bot/data/backgrounds/unsponsored.json",
    "Ustalavic Academic": "./pathfinder_bot/data/backgrounds/ustalavic-academic.json",
    "Varisian Wanderer": "./pathfinder_bot/data/backgrounds/varisian-wanderer.json",
    "Verduran City Folk": "./pathfinder_bot/data/backgrounds/verduran-city-folk.json",
    "Vidrian Reformer": "./pathfinder_bot/data/backgrounds/vidrian-reformer.json",
    "Wandering Libertine": "./pathfinder_bot/data/backgrounds/wandering-libertine.json",
    "Wandering Preacher": "./pathfinder_bot/data/backgrounds/wandering-preacher.json",
    "Wanderlust": "./pathfinder_bot/data/backgrounds/wanderlust.json",
    "Wanted Witness": "./pathfinder_bot/data/backgrounds/wanted-witness.json",
    "Ward": "./pathfinder_bot/data/backgrounds/ward.json",
    "Warded by Kami": "./pathfinder_bot/data/backgrounds/warded-by-kami.json",
    "Warrior": "./pathfinder_bot/data/backgrounds/warrior.json",
    "Waste Walker": "./pathfinder_bot/data/backgrounds/waste-walker.json",
    "Weaver": "./pathfinder_bot/data/backgrounds/weaver.json",
    "Whispering Way Scion": "./pathfinder_bot/data/backgrounds/whispering-way-scion.json",
    "Wildwood Local": "./pathfinder_bot/data/backgrounds/wildwood-local.json",
    "Willing Host": "./pathfinder_bot/data/backgrounds/willing-host.json",
    "Willowshore Urchin": "./pathfinder_bot/data/backgrounds/willowshore-urchin.json",
    "Winter's Child": "./pathfinder_bot/data/backgrounds/winters-child.json",
    "Wish for Riches": "./pathfinder_bot/data/backgrounds/wish-for-riches.json",
    "Wished Alive": "./pathfinder_bot/data/backgrounds/wished-alive.json",
    "Witch Wary": "./pathfinder_bot/data/backgrounds/witch-wary.json",
    "Witchlight Follower": "./pathfinder_bot/data/backgrounds/witchlight-follower.json",
    "Wonder Taster": "./pathfinder_bot/data/backgrounds/wonder-taster.json",
    "Wood Warden": "./pathfinder_bot/data/backgrounds/wood-warden.json",
    "Writ in the Stars": "./pathfinder_bot/data/backgrounds/writ-in-the-stars.json",
    "Zodiac Bound": "./pathfinder_bot/data/backgrounds/zodiac-bound.json",
}

CLASS_LIST = {
    "Alchemist": "./pathfinder_bot/data/classes/alchemist.json",
    "Animist": "./pathfinder_bot/data/classes/animist.json",
    "Barbarian": "./pathfinder_bot/data/classes/barbarian.json",
    "Bard": "./pathfinder_bot/data/classes/bard.json",
    "Champion": "./pathfinder_bot/data/classes/champion.json",
    "Cleric": "./pathfinder_bot/data/classes/cleric.json",
    "Druid": "./pathfinder_bot/data/classes/druid.json",
    "Exemplar": "./pathfinder_bot/data/classes/exemplar.json",
    "Fighter": "./pathfinder_bot/data/classes/fighter.json",
    "Gunslinger": "./pathfinder_bot/data/classes/gunslinger.json",
    "Inventor": "./pathfinder_bot/data/classes/inventor.json",
    "Investigator": "./pathfinder_bot/data/classes/investigator.json",
    "Kineticist": "./pathfinder_bot/data/classes/kineticist.json",
    "Magus": "./pathfinder_bot/data/classes/magus.json",
    "Monk": "./pathfinder_bot/data/classes/monk.json",
    "Oracle": "./pathfinder_bot/data/classes/oracle.json",
    "Psychic": "./pathfinder_bot/data/classes/psychic.json",
    "Ranger": "./pathfinder_bot/data/classes/ranger.json",
    "Rogue": "./pathfinder_bot/data/classes/rogue.json",
    "Sorcerer": "./pathfinder_bot/data/classes/sorcerer.json",
    "Summoner": "./pathfinder_bot/data/classes/summoner.json",
    "Swashbuckler": "./pathfinder_bot/data/classes/swashbuckler.json",
    "Thaumaturge": "./pathfinder_bot/data/classes/thaumaturge.json",
    "Witch": "./pathfinder_bot/data/classes/witch.json",
    "Wizard": "./pathfinder_bot/data/classes/wizard.json",
}
